# Generated by Django 4.2.25 on 2025-11-03 19:18

from django.db import migrations
from datetime import datetime


def backfill_status_in_batches(apps, schema_editor):
    """
    Backfill status field in small batches to avoid long-running transactions.
    This keeps each transaction short (~1 second) so other queries can proceed.
    """
    SmallUser = apps.get_model('demoapp', 'SmallUser')
    LargeUser = apps.get_model('demoapp', 'LargeUser')

    batch_size = 10000

    print(f"\n[{datetime.now().strftime('%H:%M:%S')}] Starting backfill for SmallUser...")
    # Backfill SmallUser (should be instant with only 10 rows)
    small_count = SmallUser.objects.filter(status__isnull=True).update(status='active')
    print(f"[{datetime.now().strftime('%H:%M:%S')}] Backfilled {small_count} SmallUser rows")

    print(f"\n[{datetime.now().strftime('%H:%M:%S')}] Starting batch backfill for LargeUser...")
    print(f"[{datetime.now().strftime('%H:%M:%S')}] Batch size: {batch_size:,} rows")

    total_backfilled = 0
    batch_num = 0

    while True:
        # Get IDs of next batch of rows that need backfilling
        batch_start = datetime.now()
        ids = list(
            LargeUser.objects.filter(status__isnull=True)
            .values_list('id', flat=True)[:batch_size]
        )

        if not ids:
            break  # No more rows to backfill

        # Update this batch
        updated = LargeUser.objects.filter(id__in=ids).update(status='active')
        total_backfilled += updated
        batch_num += 1

        batch_duration = (datetime.now() - batch_start).total_seconds()

        # Log progress every 10 batches or every 100k rows
        if batch_num % 10 == 0 or total_backfilled % 100000 == 0:
            print(f"[{datetime.now().strftime('%H:%M:%S')}] Batch {batch_num}: "
                  f"Updated {updated:,} rows in {batch_duration:.2f}s. "
                  f"Total: {total_backfilled:,} rows")

    print(f"\n[{datetime.now().strftime('%H:%M:%S')}] Backfill complete!")
    print(f"Total LargeUser rows backfilled: {total_backfilled:,}")
    print(f"Total batches: {batch_num}")


def reverse_backfill(apps, schema_editor):
    """Reverse operation: set all status fields back to NULL."""
    SmallUser = apps.get_model('demoapp', 'SmallUser')
    LargeUser = apps.get_model('demoapp', 'LargeUser')

    SmallUser.objects.all().update(status=None)
    LargeUser.objects.all().update(status=None)


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0002_largeuser_status_smalluser_status'),
    ]

    operations = [
        migrations.RunPython(backfill_status_in_batches, reverse_backfill),
    ]
