# Generated by Django 4.2.25 on 2025-11-03 19:25

from django.db import migrations, models
from datetime import datetime


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0003_backfill_status_field'),
    ]

    operations = [
        migrations.RunPython(
            lambda apps, schema_editor: print(f"\n[{datetime.now().strftime('%H:%M:%S')}] Starting Step 3: Adding NOT NULL constraint to status field..."),
            migrations.RunPython.noop
        ),
        migrations.AlterField(
            model_name='smalluser',
            name='status',
            field=models.CharField(default='active', max_length=20),
        ),
        migrations.RunPython(
            lambda apps, schema_editor: print(f"[{datetime.now().strftime('%H:%M:%S')}] SmallUser status field altered to NOT NULL"),
            migrations.RunPython.noop
        ),
        migrations.AlterField(
            model_name='largeuser',
            name='status',
            field=models.CharField(default='active', max_length=20),
        ),
        migrations.RunPython(
            lambda apps, schema_editor: print(f"[{datetime.now().strftime('%H:%M:%S')}] LargeUser status field altered to NOT NULL"),
            migrations.RunPython.noop
        ),
        migrations.RunPython(
            lambda apps, schema_editor: print(f"[{datetime.now().strftime('%H:%M:%S')}] Step 3 complete! NOT NULL constraint added instantly.\n"),
            migrations.RunPython.noop
        ),
    ]
