# Generated by Django 5.2.7 on 2025-10-07 17:05

import django.db.models.deletion
from django.db import migrations, models
from datetime import datetime


def log_smallorder_start(apps, schema_editor):
    print(f"\n[{datetime.now().strftime('%Y-%m-%d %H:%M:%S.%f')[:-3]}] Adding nullable FK customer to SmallOrder...")


def log_smallorder_end(apps, schema_editor):
    print(f"[{datetime.now().strftime('%Y-%m-%d %H:%M:%S.%f')[:-3]}] ✓ SmallOrder FK added\n")


def log_largeorder_start(apps, schema_editor):
    print(f"[{datetime.now().strftime('%Y-%m-%d %H:%M:%S.%f')[:-3]}] Adding nullable FK customer to LargeOrder...")


def log_largeorder_end(apps, schema_editor):
    print(f"[{datetime.now().strftime('%Y-%m-%d %H:%M:%S.%f')[:-3]}] ✓ LargeOrder FK added\n")


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(log_smallorder_start, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='smallorder',
            name='customer_id',
        ),
        migrations.AddField(
            model_name='smallorder',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='demoapp.customer'),
        ),
        migrations.RunPython(log_smallorder_end, migrations.RunPython.noop),

        migrations.RunPython(log_largeorder_start, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='largeorder',
            name='customer_id',
        ),
        migrations.AddField(
            model_name='largeorder',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='demoapp.customer'),
        ),
        migrations.RunPython(log_largeorder_end, migrations.RunPython.noop),
    ]
