# Generated by Django 5.2.7 on 2025-10-07 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LargeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'large_record',
            },
        ),
        migrations.CreateModel(
            name='SmallRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'small_record',
            },
        ),
    ]
