# Generated by Django 5.2.7 on 2025-10-07 08:57

from django.db import migrations, models
from datetime import datetime


def log_migration_start(apps, schema_editor):
    print(f"\n{'='*60}")
    print(f"[{datetime.now().strftime('%Y-%m-%d %H:%M:%S')}] Starting migration: Changing column type")
    print(f"{'='*60}\n")


def log_smallrecord_start(apps, schema_editor):
    print(f"[{datetime.now().strftime('%Y-%m-%d %H:%M:%S.%f')[:-3]}] Changing SmallRecord.created_at from VARCHAR to DATETIME...")


def log_smallrecord_end(apps, schema_editor):
    print(f"[{datetime.now().strftime('%Y-%m-%d %H:%M:%S.%f')[:-3]}] ✓ SmallRecord column type changed\n")


def log_largerecord_start(apps, schema_editor):
    print(f"[{datetime.now().strftime('%Y-%m-%d %H:%M:%S.%f')[:-3]}] Changing LargeRecord.created_at from VARCHAR to DATETIME...")


def log_largerecord_end(apps, schema_editor):
    print(f"[{datetime.now().strftime('%Y-%m-%d %H:%M:%S.%f')[:-3]}] ✓ LargeRecord column type changed\n")


def log_migration_end(apps, schema_editor):
    print(f"{'='*60}")
    print(f"[{datetime.now().strftime('%Y-%m-%d %H:%M:%S')}] Migration completed")
    print(f"{'='*60}\n")


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(log_migration_start, migrations.RunPython.noop),

        migrations.RunPython(log_smallrecord_start, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='smallrecord',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.RunPython(log_smallrecord_end, migrations.RunPython.noop),

        migrations.RunPython(log_largerecord_start, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='largerecord',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.RunPython(log_largerecord_end, migrations.RunPython.noop),

        migrations.RunPython(log_migration_end, migrations.RunPython.noop),
    ]
