# Generated by Django 5.2.7 on 2025-10-07 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0002_alter_largerecord_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='largerecord',
            name='created_at_new',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='smallrecord',
            name='created_at_new',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
