# Generated by Django 5.2.7 on 2025-10-07 09:01

from django.db import migrations
from datetime import datetime


def backfill_created_at_new(apps, schema_editor):
    """
    Copy data from created_at to created_at_new in batches.
    This is the SAFE way to change column types.
    """
    SmallRecord = apps.get_model('demoapp', 'SmallRecord')
    LargeRecord = apps.get_model('demoapp', 'LargeRecord')

    batch_size = 100000

    # Backfill SmallRecord (fast)
    print(f"\n[{datetime.now().strftime('%Y-%m-%d %H:%M:%S.%f')[:-3]}] Backfilling created_at_new in SmallRecord...")
    for record in SmallRecord.objects.filter(created_at_new__isnull=True):
        record.created_at_new = record.created_at
        record.save(update_fields=['created_at_new'])
    print(f"[{datetime.now().strftime('%Y-%m-%d %H:%M:%S.%f')[:-3]}] ✓ SmallRecord backfill completed\n")

    # Backfill LargeRecord in batches (safe)
    print(f"[{datetime.now().strftime('%Y-%m-%d %H:%M:%S.%f')[:-3]}] Backfilling created_at_new in LargeRecord (in batches)...")
    total_updated = 0

    while True:
        # Get IDs of rows that need updating
        ids_to_update = list(
            LargeRecord.objects.filter(created_at_new__isnull=True).values_list('id', flat=True)[:batch_size]
        )

        if not ids_to_update:
            break

        # Fetch and update this batch
        records = LargeRecord.objects.filter(id__in=ids_to_update)
        for record in records:
            record.created_at_new = record.created_at

        LargeRecord.objects.bulk_update(records, ['created_at_new'], batch_size=batch_size)
        total_updated += len(ids_to_update)

        # Show progress every 1M rows
        if total_updated % 1000000 == 0:
            print(f"  [{datetime.now().strftime('%Y-%m-%d %H:%M:%S')}] Backfilled {total_updated:,} rows...")

    print(f"[{datetime.now().strftime('%Y-%m-%d %H:%M:%S.%f')[:-3]}] ✓ Updated {total_updated:,} LargeRecord records\n")


def reverse_backfill(apps, schema_editor):
    """Reverse operation: clear created_at_new"""
    SmallRecord = apps.get_model('demoapp', 'SmallRecord')
    LargeRecord = apps.get_model('demoapp', 'LargeRecord')

    SmallRecord.objects.all().update(created_at_new=None)
    LargeRecord.objects.all().update(created_at_new=None)


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0003_largerecord_created_at_new_and_more'),
    ]

    operations = [
        migrations.RunPython(backfill_created_at_new, reverse_backfill),
    ]
