# Generated by Django 5.2.7 on 2025-10-07 09:05

from django.db import migrations, models
from datetime import datetime


def log_smallrecord_start(apps, schema_editor):
    print(f"\n[{datetime.now().strftime('%Y-%m-%d %H:%M:%S.%f')[:-3]}] Enforcing NOT NULL on SmallRecord.created_at_new...")


def log_smallrecord_end(apps, schema_editor):
    print(f"[{datetime.now().strftime('%Y-%m-%d %H:%M:%S.%f')[:-3]}] ✓ SmallRecord NOT NULL constraint enforced\n")


def log_largerecord_start(apps, schema_editor):
    print(f"[{datetime.now().strftime('%Y-%m-%d %H:%M:%S.%f')[:-3]}] Enforcing NOT NULL on LargeRecord.created_at_new...")


def log_largerecord_end(apps, schema_editor):
    print(f"[{datetime.now().strftime('%Y-%m-%d %H:%M:%S.%f')[:-3]}] ✓ LargeRecord NOT NULL constraint enforced\n")


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0004_backfill_created_at_new'),
    ]

    operations = [
        migrations.RunPython(log_smallrecord_start, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='smallrecord',
            name='created_at_new',
            field=models.DateTimeField(),
        ),
        migrations.RunPython(log_smallrecord_end, migrations.RunPython.noop),

        migrations.RunPython(log_largerecord_start, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='largerecord',
            name='created_at_new',
            field=models.DateTimeField(),
        ),
        migrations.RunPython(log_largerecord_end, migrations.RunPython.noop),
    ]
