# Generated by Django 5.2.7 on 2025-11-03 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='largeuser',
            name='status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='smalluser',
            name='status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
