# Generated by Django 5.2.7 on 2025-11-03 18:00

from django.db import migrations, models
from datetime import datetime


def log_migration_start(apps, schema_editor):
    print(f"\n{'='*60}")
    print(f"[{datetime.now().strftime('%Y-%m-%d %H:%M:%S')}] Starting migration: Adding NOT NULL constraint to status field")
    print(f"{'='*60}\n")


def log_smalluser_start(apps, schema_editor):
    print(f"[{datetime.now().strftime('%Y-%m-%d %H:%M:%S.%f')[:-3]}] Adding NOT NULL constraint to SmallUser.status...")


def log_smalluser_end(apps, schema_editor):
    print(f"[{datetime.now().strftime('%Y-%m-%d %H:%M:%S.%f')[:-3]}] ✓ SmallUser constraint added\n")


def log_largeuser_start(apps, schema_editor):
    print(f"[{datetime.now().strftime('%Y-%m-%d %H:%M:%S.%f')[:-3]}] Adding NOT NULL constraint to LargeUser.status...")


def log_largeuser_end(apps, schema_editor):
    print(f"[{datetime.now().strftime('%Y-%m-%d %H:%M:%S.%f')[:-3]}] ✓ LargeUser constraint added\n")


def log_migration_end(apps, schema_editor):
    print(f"{'='*60}")
    print(f"[{datetime.now().strftime('%Y-%m-%d %H:%M:%S')}] Migration completed")
    print(f"{'='*60}\n")


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0002_largeuser_status_smalluser_status'),
    ]

    operations = [
        migrations.RunPython(log_migration_start, migrations.RunPython.noop),

        migrations.RunPython(log_smalluser_start, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='smalluser',
            name='status',
            field=models.CharField(default='active', max_length=20),
        ),
        migrations.RunPython(log_smalluser_end, migrations.RunPython.noop),

        migrations.RunPython(log_largeuser_start, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='largeuser',
            name='status',
            field=models.CharField(default='active', max_length=20),
        ),
        migrations.RunPython(log_largeuser_end, migrations.RunPython.noop),

        migrations.RunPython(log_migration_end, migrations.RunPython.noop),
    ]
