# Generated by Django 5.2.8 on 2025-11-07 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='largerecord',
            name='created_at_new',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='smallrecord',
            name='created_at_new',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
