# Generated by Django 4.2.25 on 2025-11-07 10:28

from django.db import migrations, models
import django.utils.timezone
from datetime import datetime


def log_start_small(apps, schema_editor):
    """Log the start time of NOT NULL enforcement for SmallRecord."""
    print(f"\n[{datetime.now().strftime('%H:%M:%S')}] Starting NOT NULL enforcement for SmallRecord...")


def log_end_small(apps, schema_editor):
    """Log the end time of NOT NULL enforcement for SmallRecord."""
    print(f"[{datetime.now().strftime('%H:%M:%S')}] SmallRecord NOT NULL enforcement complete!")


def log_start_large(apps, schema_editor):
    """Log the start time of NOT NULL enforcement for LargeRecord."""
    print(f"\n[{datetime.now().strftime('%H:%M:%S')}] Starting NOT NULL enforcement for LargeRecord...")


def log_end_large(apps, schema_editor):
    """Log the end time of NOT NULL enforcement for LargeRecord."""
    print(f"[{datetime.now().strftime('%H:%M:%S')}] LargeRecord NOT NULL enforcement complete!")


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0003_backfill_created_at_new'),
    ]

    operations = [
        migrations.RunPython(log_start_large, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='largerecord',
            name='created_at_new',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.RunPython(log_end_large, migrations.RunPython.noop),

        migrations.RunPython(log_start_small, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='smallrecord',
            name='created_at_new',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.RunPython(log_end_small, migrations.RunPython.noop),
    ]
