# Generated by Django 5.2.7 on 2025-10-07 10:10

from django.db import migrations
from datetime import datetime


def log_smallproduct_start(apps, schema_editor):
    print(f"\n[{datetime.now().strftime('%Y-%m-%d %H:%M:%S.%f')[:-3]}] Dropping legacy_code column from SmallProduct...")


def log_smallproduct_end(apps, schema_editor):
    print(f"[{datetime.now().strftime('%Y-%m-%d %H:%M:%S.%f')[:-3]}] ✓ SmallProduct column dropped\n")


def log_largeproduct_start(apps, schema_editor):
    print(f"[{datetime.now().strftime('%Y-%m-%d %H:%M:%S.%f')[:-3]}] Dropping legacy_code column from LargeProduct...")


def log_largeproduct_end(apps, schema_editor):
    print(f"[{datetime.now().strftime('%Y-%m-%d %H:%M:%S.%f')[:-3]}] ✓ LargeProduct column dropped\n")


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(log_smallproduct_start, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='smallproduct',
            name='legacy_code',
        ),
        migrations.RunPython(log_smallproduct_end, migrations.RunPython.noop),

        migrations.RunPython(log_largeproduct_start, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='largeproduct',
            name='legacy_code',
        ),
        migrations.RunPython(log_largeproduct_end, migrations.RunPython.noop),
    ]
