# Generated by Django 5.2.7 on 2025-10-06 09:18

from django.db import migrations, models
from datetime import datetime


def log_migration_start(apps, schema_editor):
    print(f"\n{'='*60}")
    print(f"[{datetime.now().strftime('%Y-%m-%d %H:%M:%S')}] Starting migration: Adding index to email field")
    print(f"{'='*60}\n")


def log_smallemail_start(apps, schema_editor):
    print(f"[{datetime.now().strftime('%Y-%m-%d %H:%M:%S.%f')[:-3]}] Adding index to SmallEmail.email...")


def log_smallemail_end(apps, schema_editor):
    print(f"[{datetime.now().strftime('%Y-%m-%d %H:%M:%S.%f')[:-3]}] ✓ SmallEmail index created\n")


def log_largeemail_start(apps, schema_editor):
    print(f"[{datetime.now().strftime('%Y-%m-%d %H:%M:%S.%f')[:-3]}] Adding index to LargeEmail.email...")


def log_largeemail_end(apps, schema_editor):
    print(f"[{datetime.now().strftime('%Y-%m-%d %H:%M:%S.%f')[:-3]}] ✓ LargeEmail index created\n")


def log_migration_end(apps, schema_editor):
    print(f"{'='*60}")
    print(f"[{datetime.now().strftime('%Y-%m-%d %H:%M:%S')}] Migration completed")
    print(f"{'='*60}\n")


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(log_migration_start, migrations.RunPython.noop),

        migrations.RunPython(log_smallemail_start, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='smallemail',
            name='email',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.RunPython(log_smallemail_end, migrations.RunPython.noop),

        migrations.RunPython(log_largeemail_start, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='largeemail',
            name='email',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.RunPython(log_largeemail_end, migrations.RunPython.noop),

        migrations.RunPython(log_migration_end, migrations.RunPython.noop),
    ]
